apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yrqu-dfodor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yrqu-dfodor
    app.kubernetes.io/part-of: devfile-sample-1
  name: devfile-sample-yrqu-dfodor
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-yrqu-dfodor
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-yrqu-dfodor
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/devfile-sample-1/devfile-sample-yrqu-dfodor@sha256:ce520700f05c9e7372430c1075a383907b973ac4139e85b4762fd914b4f76d5c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
