apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yrqu-dfodor
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/devfile-sample-1/devfile-sample-yrqu-dfodor@sha256:ce520700f05c9e7372430c1075a383907b973ac4139e85b4762fd914b4f76d5c
        name: my-nodejs
        resources: {}
status: {}
